import { PNG } from "pngjs";

const base = {
  angle: 0,
  strokeColor: "#000000",
  backgroundColor: "transparent",
  fillStyle: "solid",
  strokeWidth: 2,
  strokeStyle: "solid",
  roughness: 0,
  opacity: 100,
  groupIds: [],
  frameId: null,
  roundness: null,
  seed: 123,
  version: 1,
  versionNonce: 1,
  isDeleted: false,
  boundElements: null,
  updated: 1,
  link: null,
  locked: false,
};

export function renderFixture() {
  const image = new PNG({ width: 2, height: 2 });
  for (let offset = 0; offset < image.data.length; offset += 4) {
    image.data.set([0, 255, 0, 255], offset);
  }
  return {
    type: "excalidraw",
    version: 2,
    elements: [
      {
        ...base,
        id: "frame",
        index: "a0",
        type: "frame",
        x: 0,
        y: 0,
        width: 200,
        height: 100,
        name: "Example",
      },
      {
        ...base,
        id: "rect",
        index: "a1",
        type: "rectangle",
        x: 10,
        y: 10,
        width: 180,
        height: 80,
        backgroundColor: "#ff0000",
        frameId: "frame",
      },
      {
        ...base,
        id: "image",
        index: "a2",
        type: "image",
        x: 20,
        y: 60,
        width: 20,
        height: 20,
        fileId: "green",
        status: "saved",
        scale: [1, 1],
        crop: null,
        frameId: "frame",
      },
      {
        ...base,
        id: "text",
        index: "a3",
        type: "text",
        x: 20,
        y: 20,
        width: 160,
        height: 25,
        text: "Local rendering",
        originalText: "Local rendering",
        fontFamily: 5,
        fontSize: 20,
        lineHeight: 1.25,
        textAlign: "left",
        verticalAlign: "top",
        containerId: null,
        autoResize: true,
        frameId: "frame",
      },
      {
        ...base,
        id: "outside",
        index: "a4",
        type: "rectangle",
        x: 400,
        y: 0,
        width: 20,
        height: 20,
        backgroundColor: "#0000ff",
      },
      {
        ...base,
        id: "deleted",
        index: "a5",
        type: "rectangle",
        x: 10000,
        y: 0,
        width: 20,
        height: 20,
        isDeleted: true,
      },
    ],
    appState: { viewBackgroundColor: "#ffffff", exportBackground: true, exportWithDarkMode: false },
    files: {
      green: {
        id: "green",
        mimeType: "image/png",
        dataURL: `data:image/png;base64,${PNG.sync.write(image).toString("base64")}`,
        created: 1,
      },
    },
  };
}

/** One Excalifont text element per line, stacked vertically, with no images or frames. */
export function textFixture(lines: string[]) {
  return {
    type: "excalidraw",
    version: 2,
    elements: lines.map((text, index) => ({
      ...base,
      id: `text${index}`,
      index: `a${index}`,
      type: "text",
      x: 0,
      y: index * 40,
      width: 300,
      height: 25,
      text,
      originalText: text,
      fontFamily: 5,
      fontSize: 20,
      lineHeight: 1.25,
      textAlign: "left",
      verticalAlign: "top",
      containerId: null,
      autoResize: true,
    })),
    appState: { viewBackgroundColor: "#ffffff" },
    files: {},
  };
}
